db_file: "bot.db"

bot_url: "https://t.me/pocketMikabot"

messages:
  responses:
    start: "Привет! Чтобы сохранить ссылки в своем Pocket аккаунте, для начало тебе необходимо дать мне на это доступ. Для этого переходи по ссылке: \n%s"
    alreadyAuthorized: "Ты уже авторизован. Прислай ссылку, а я ее сохраню"
    savedSuccessfully: "Ссылка успешно сохранена!"
    unknownCommand: "Я не знаю такой команды :("
  errors:
    default: "Произошла неизвестная ошибка"
    invalidUrl: "Это невалидная ссылка"
    unauthorized: "Ты не авторизован! Используй команду /start"
    unableToSave: "Увы, не удалось сохранить ссылку. Попрбуй еще раз позже."  